name: cross compile build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - gcc_prefix: arm-linux-gnueabi
            arch: arm

    steps:
    - uses: actions/checkout@v4

    - name: install dependecies
      run: |
        sudo apt-get update
        sudo apt-get install --yes "gcc-${{ matrix.platform.gcc_prefix }}" libncurses5-dev

    - name: configure
      run: |
        export ARCH="${{ matrix.platform.arch }}"
        export CROSS_COMPILE="${{ matrix.platform.gcc_prefix }}-"

        if [ -f busybox.config ]; then
          echo "building from busybox.config"
          cp busybox.config .config
          yes "" | make oldconfig
        else
          echo "building from defaults"
          make defconfig
        fi

    - name: make
      run: |
        export ARCH="${{ matrix.platform.arch }}"
        export CROSS_COMPILE="${{ matrix.platform.gcc_prefix }}-"

        # make -j$(nproc) install
        make install
