name: cross compile build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - gcc_prefix: arm-linux-gnueabi
            arch: arm

    steps:
    - uses: actions/checkout@v4

    - name: install dependecies
      run: |
        sudo apt-get update
        sudo apt-get install --yes "gcc-${{ matrix.platform.gcc_prefix }}" libncurses5-dev

    - name: make
      run: |
        export ARCH="${{ matrix.platform.arch }}"
        export CROSS_COMPILE="${{ matrix.platform.gcc_prefix }}-"

        make distclean
        make rinkhals_defconfig
        make -j$(nproc) install

    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: busybox-${{ matrix.platform.arch }}
        path: |
          _install/bin/busybox
