name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - arm
          - amd64

    steps:
    - uses: actions/checkout@v4

    - name: install dependecies
      run: |
        apt-get update
        apt-get install -y gcc-"${{ matrix.arch }}"-linux-gnueabi libncurses5-dev

    - name: configure
      run: |
        export ARCH="${{ matrix.arch }}"
        export CROSS_COMPILE=gcc-"${{ matrix.arch }}"-linux-gnueabi-

        if [[ -f "busybox.config" ]; then
          echo "building from busybox.config"
          cp busybox.config .config
          yes "" | make oldconfig
        else
          echo "building from defaults"
          make defconfig
        fi

    - name: make
      run: |
        export ARCH="${{ matrix.arch }}"
        export CROSS_COMPILE=gcc-"${{ matrix.arch }}"-linux-gnueabi-

        make -j$(nproc) install
